<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Actions' => 'Ações',
    'Add category' => 'Adicionar categoria',
    'Add post' => 'Adicionar postagem',
    'Add subcategory' => 'Adicionar subcategoria',
    'Add, edit, delete, enable and disable categories.' => 'Adicionar, editar, excluir, ativar e desativar categorias.',
    'Are you sure to delete this user?' => 'Tem certeza de que deseja excluir este usuário?',
    'Are you sure to disable this category?' => 'Tem certeza de que deseja desativar esta categoria?',
    'Are you sure to enable this category?' => 'Tem certeza de que deseja ativar esta categoria?',
    'By Category: {category} ({post.count})' => 'Por categoria: {category} ({post.count})',
    'By Post' => 'Por postagem',
    'Categories' => 'Categorias',
    'Category' => 'Categoria',
    'Content Short' => 'Conteúdo Resumido',
    'Create post' => 'Criar postagem',
    'Date' => 'Data',
    'Delete' => 'Excluir',
    'Description' => 'Descrição',
    'Disable category' => 'Desativar categoria',
    'Discover new releases, fresh articles, updated wikis, and engage in general' => 'Descubra novos lançamentos, artigos atualizados, wikis atualizados e participe em geral',
    'Enable category' => 'Ativar categoria',
    'Enter description Here.' => 'Digite a descrição aqui.',
    'Enter slug Here.' => 'Digite o slug aqui.',
    'Enter title Here.' => 'Digite o título aqui.',
    'Explore now' => 'Explore agora',
    'Filter by Category: {category}' => 'Filtrar por categoria: {category}',
    'Follow me' => 'Siga-me',
    'Id' => 'Id',
    'Latest' => 'Mais recente',
    'Latest ({post.count})' => 'Mais recente ({post.count})',
    'Parent category:' => 'Categoria pai:',
    'Please fill out the following fields to category' => 'Por favor, preencha os seguintes campos para a categoria',
    'Please fill out the following fields to create post.' => 'Por favor, preencha os seguintes campos para criar a postagem.',
    'Posts' => 'Postagens',
    'Read more' => 'Leia mais',
    'Register' => 'Registrar',
    'Register category' => 'Registrar categoria',
    'Save' => 'Salvar',
    'Select category' => 'Selecionar categoria',
    'Seo Description' => 'Descrição SEO',
    'Seo H1' => 'SEO H1',
    'Seo Keywords' => 'Palavras-chave SEO',
    'Seo Title' => 'Título SEO',
    'Seo texts' => 'Textos SEO',
    'Slug' => 'Slug',
    'Status' => 'Status',
    'Stay updated with the latest news and announcements on YiiFramework.' => 'Mantenha-se atualizado com as últimas notícias e anúncios sobre YiiFramework.',
    'Subcategory' => 'Subcategoria',
    'Tags' => 'Tags',
    'This category does not exist.' => 'Esta categoria não existe.',
    'This title has already been taken.' => 'Este título já foi utilizado.',
    'Title' => 'Título',
    'Update' => 'Atualizar',
    'Update category' => 'Atualizar categoria',
    'Update posts' => 'Atualizar postagens',
    'Your category and its sub categories have been successfully deleted.' => 'Sua categoria e suas subcategorias foram excluídas com sucesso.',
    'Your category has been successfully deleted.' => 'Sua categoria foi excluída com sucesso.',
    'Your category has been successfully disabled.' => 'Sua categoria foi desativada com sucesso.',
    'Your category has been successfully enabled.' => 'Sua categoria foi ativada com sucesso.',
    'Your category has been successfully updated.' => 'Sua categoria foi atualizada com sucesso.',
    'Your category has not been deleted.' => 'Sua categoria não foi excluída.',
    'Your category has not been found.' => 'Sua categoria não foi encontrada.',
    'Your principal category has been successfully registered.' => 'Sua categoria principal foi registrada com sucesso.',
    'Your sub category has been successfully registered.' => 'Sua subcategoria foi registrada com sucesso.',
    'created_at' => 'criado_em',
    'discussions within the Yii community. ' => 'discussões dentro da comunidade Yii.',
    'tags' => 'tags',
];
