<?php

declare(strict_types=1);

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Actions' => 'Действия',
    'Add category' => 'Добавить категорию',
    'Add post' => 'Добавить пост',
    'Add subcategory' => 'Добавить подкатегорию',
    'Add, edit, delete, enable and disable categories.' => 'Добавить, изменить, удалить, включить и отключить категории.',
    'All posts' => 'Все посты',
    'Archive' => 'Архив',
    'Archive|YiiVerse Blog' => 'Архив|YiiVerse Blog',
    'Are you sure to delete this user?' => 'Вы уверены, что хотите удалить этого пользователя?',
    'Are you sure to disable this category?' => 'Вы уверены, что хотите отключить эту категорию?',
    'Are you sure to enable this category?' => 'Вы уверены, что хотите включить эту категорию?',
    'Categories' => 'Категории',
    'Category' => 'Категория',
    'Content Short' => 'Краткое содержание',
    'Create post' => 'Создать пост',
    'Date' => 'Дата',
    'Delete' => 'Удалить',
    'Description' => 'Описание',
    'Disable category' => 'Отключить категорию',
    'Enable category' => 'Включить категорию',
    'Enter description Here.' => 'Введите описание здесь.',
    'Enter slug Here.' => 'Введите слаг здесь.',
    'Enter title Here.' => 'Введите заголовок здесь.',
    'Id' => 'ID',
    'Parent category:' => 'Родительская категория:',
    'Please fill out the following fields to category' => 'Пожалуйста, заполните следующие поля для категории',
    'Please fill out the following fields to create post.' => 'Пожалуйста, заполните следующие поля для создания поста.',
    'Posts' => 'Посты',
    'Register' => 'Зарегистрировать',
    'Register category' => 'Зарегистрировать категорию',
    'Save' => 'Сохранить',
    'Select category' => 'Выберите категорию',
    'Seo Description' => 'SEO Описание',
    'Seo H1' => 'SEO H1',
    'Seo Keywords' => 'SEO Ключевые слова',
    'Seo Title' => 'SEO Заголовок',
    'Seo texts' => 'SEO Тексты',
    'Slug' => 'Слаг',
    'Status' => 'Статус',
    'Subcategory' => 'Подкатегория',
    'Tags' => 'Теги',
    'This category does not exist.' => 'Эта категория не существует.',
    'This title has already been taken.' => 'Этот заголовок уже занят.',
    'Title' => 'Заголовок',
    'Update' => 'Обновить',
    'Update category' => 'Обновить категорию',
    'Update posts' => 'Обновить посты',
    'YiiVerse Blog' => 'YiiVerse Blog',
    'Your category and its sub categories have been successfully deleted.' => 'Ваша категория и ее подкатегории успешно удалены.',
    'Your category has been successfully deleted.' => 'Ваша категория успешно удалена.',
    'Your category has been successfully disabled.' => 'Ваша категория успешно отключена.',
    'Your category has been successfully enabled.' => 'Ваша категория успешно включена.',
    'Your category has been successfully updated.' => 'Ваша категория успешно обновлена.',
    'Your category has not been deleted.' => 'Ваша категория не была удалена.',
    'Your category has not been found.' => 'Ваша категория не найдена.',
    'Your principal category has been successfully registered.' => 'Ваша основная категория успешно зарегистрирована.',
    'Your sub category has been successfully registered.' => 'Ваша подкатегория успешно зарегистрирована.',
    'content_short' => 'краткое_содержание',
    'created_at' => 'создано_в',
    'tags' => 'теги',
];
