<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Actions' => 'Actions',
    'Add category' => 'Ajouter une catégorie',
    'Add post' => 'Ajouter une publication',
    'Add subcategory' => 'Ajouter une sous-catégorie',
    'Add, edit, delete, enable and disable categories.' => 'Ajouter, modifier, supprimer, activer et désactiver des catégories.',
    'Are you sure to delete this user?' => 'Êtes-vous sûr de vouloir supprimer cet utilisateur ?',
    'Are you sure to disable this category?' => 'Êtes-vous sûr de vouloir désactiver cette catégorie ?',
    'Are you sure to enable this category?' => 'Êtes-vous sûr de vouloir activer cette catégorie ?',
    'By Category: {category} ({post.count})' => 'Par catégorie : {category} ({post.count})',
    'By Post' => 'Par publication',
    'Categories' => 'Catégories',
    'Category' => 'Catégorie',
    'Content Short' => 'Contenu court',
    'Create post' => 'Créer une publication',
    'Date' => 'Date',
    'Delete' => 'Supprimer',
    'Description' => 'Description',
    'Disable category' => 'Désactiver la catégorie',
    'Enable category' => 'Activer la catégorie',
    'Enter description Here.' => 'Entrez la description ici.',
    'Enter slug Here.' => 'Entrez le slug ici.',
    'Enter title Here.' => 'Entrez le titre ici.',
    'Filter by Category: {category}' => 'Filtrer par catégorie : {category}',
    'Follow me' => 'Suis-moi',
    'Id' => 'Id',
    'Latest' => 'Dernier',
    'Latest ({post.count})' => 'Dernier ({post.count})',
    'Parent category:' => 'Catégorie parente :',
    'Please fill out the following fields to category' => 'Veuillez remplir les champs suivants pour la catégorie',
    'Please fill out the following fields to create post.' => 'Veuillez remplir les champs suivants pour créer la publication.',
    'Posts' => 'Publications',
    'Read more' => 'Lire la suite',
    'Register' => 'S\'inscrire',
    'Register category' => 'Enregistrer la catégorie',
    'Save' => 'Enregistrer',
    'Select category' => 'Sélectionner la catégorie',
    'Seo Description' => 'Description SEO',
    'Seo H1' => 'SEO H1',
    'Seo Keywords' => 'Mots-clés SEO',
    'Seo Title' => 'Titre SEO',
    'Seo texts' => 'Textes SEO',
    'Slug' => 'Slug',
    'Status' => 'Statut',
    'Subcategory' => 'Sous-catégorie',
    'Tags' => 'Tags',
    'This category does not exist.' => 'Cette catégorie n\'existe pas.',
    'This title has already been taken.' => 'Ce titre est déjà pris.',
    'Title' => 'Titre',
    'Update' => 'Mettre à jour',
    'Update category' => 'Mettre à jour la catégorie',
    'Update posts' => 'Mettre à jour les publications',
    'Your category and its sub categories have been successfully deleted.' => 'Votre catégorie et ses sous-catégories ont été supprimées avec succès.',
    'Your category has been successfully deleted.' => 'Votre catégorie a été supprimée avec succès.',
    'Your category has been successfully disabled.' => 'Votre catégorie a été désactivée avec succès.',
    'Your category has been successfully enabled.' => 'Votre catégorie a été activée avec succès.',
    'Your category has been successfully updated.' => 'Votre catégorie a été mise à jour avec succès.',
    'Your category has not been deleted.' => 'Votre catégorie n\'a pas été supprimée.',
    'Your category has not been found.' => 'Votre catégorie n\'a pas été trouvée.',
    'Your principal category has been successfully registered.' => 'Votre catégorie principale a été enregistrée avec succès.',
    'Your sub category has been successfully registered.' => 'Votre sous-catégorie a été enregistrée avec succès.',
    'created_at' => 'créé_à',
    'tags' => 'tags',
];
