<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Actions' => '操作',
    'Add category' => '添加类别',
    'Add post' => '添加文章',
    'Add subcategory' => '添加子类别',
    'Add, edit, delete, enable and disable categories.' => '添加、编辑、删除、启用和禁用类别。',
    'Are you sure to delete this user?' => '您确定要删除此用户吗？',
    'Are you sure to disable this category?' => '您确定要禁用此类别吗？',
    'Are you sure to enable this category?' => '您确定要启用此类别吗？',
    'By Category: {category} ({post.count})' => '按类别：{category}（{post.count}）',
    'By Post' => '按帖子',
    'Categories' => '类别',
    'Category' => '类别',
    'Content Short' => '内容简介',
    'Create post' => '创建文章',
    'Date' => '日期',
    'Delete' => '删除',
    'Description' => '描述',
    'Disable category' => '禁用类别',
    'Discover new releases, fresh articles, updated wikis, and engage in general' => '发现新版本、新鲜文章、更新的 Wiki，并参与一般',
    'Enable category' => '启用类别',
    'Enter description Here.' => '在此输入描述。',
    'Enter slug Here.' => '在此输入 slug。',
    'Enter title Here.' => '在此输入标题。',
    'Explore now' => '现在探索',
    'Filter by Category: {category}' => '按类别筛选：{category}',
    'Follow me' => '跟着我',
    'Id' => 'ID',
    'Latest' => '最新的',
    'Latest ({post.count})' => '最新的（{post.count}）',
    'Parent category:' => '父类别：',
    'Please fill out the following fields to category' => '请填写以下字段以创建类别',
    'Please fill out the following fields to create post.' => '请填写以下字段以创建文章。',
    'Posts' => '文章',
    'Read more' => '阅读更多',
    'Register' => '注册',
    'Register category' => '注册类别',
    'Save' => '保存',
    'Select category' => '选择类别',
    'Seo Description' => 'SEO 描述',
    'Seo H1' => 'SEO H1',
    'Seo Keywords' => 'SEO 关键词',
    'Seo Title' => 'SEO 标题',
    'Seo texts' => 'SEO 文本',
    'Slug' => 'Slug',
    'Status' => '状态',
    'Stay updated with the latest news and announcements on YiiFramework.' => '及时了解 YiiFramework 的最新新闻和公告。',
    'Subcategory' => '子类别',
    'Tags' => '标签',
    'This category does not exist.' => '此类别不存在。',
    'This title has already been taken.' => '此标题已被使用。',
    'Title' => '标题',
    'Update' => '更新',
    'Update category' => '更新类别',
    'Update posts' => '更新文章',
    'Your category and its sub categories have been successfully deleted.' => '您的类别及其子类别已成功删除。',
    'Your category has been successfully deleted.' => '您的类别已成功删除。',
    'Your category has been successfully disabled.' => '您的类别已成功禁用。',
    'Your category has been successfully enabled.' => '您的类别已成功启用。',
    'Your category has been successfully updated.' => '您的类别已成功更新。',
    'Your category has not been deleted.' => '您的类别未被删除。',
    'Your category has not been found.' => '未找到您的类别。',
    'Your principal category has been successfully registered.' => '您的主类别已成功注册。',
    'Your sub category has been successfully registered.' => '您的子类别已成功注册。',
    'created_at' => '创建于',
    'discussions within the Yii community. ' => 'Yii 社区内的讨论',
    'tags' => '标签',
];
