<?php

declare(strict_types=1);

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Actions' => 'Aktionen',
    'Add category' => 'Kategorie hinzufügen',
    'Add post' => 'Beitrag hinzufügen',
    'Add subcategory' => 'Unterkategorie hinzufügen',
    'Add, edit, delete, enable and disable categories.' => 'Kategorien hinzufügen, bearbeiten, löschen, aktivieren und deaktivieren.',
    'All posts' => 'Alle Beiträge',
    'Archive' => 'Archiv',
    'Archive|YiiVerse Blog' => 'Archiv|YiiVerse Blog',
    'Are you sure to delete this user?' => 'Sind Sie sicher, diesen Benutzer zu löschen?',
    'Are you sure to disable this category?' => 'Sind Sie sicher, diese Kategorie zu deaktivieren?',
    'Are you sure to enable this category?' => 'Sind Sie sicher, diese Kategorie zu aktivieren?',
    'Categories' => 'Kategorien',
    'Category' => 'Kategorie',
    'Content Short' => 'Kurzer Inhalt',
    'Create post' => 'Beitrag erstellen',
    'Date' => 'Datum',
    'Delete' => 'Löschen',
    'Description' => 'Beschreibung',
    'Disable category' => 'Kategorie deaktivieren',
    'Enable category' => 'Kategorie aktivieren',
    'Enter description Here.' => 'Beschreibung hier eingeben.',
    'Enter slug Here.' => 'Slug hier eingeben.',
    'Enter title Here.' => 'Titel hier eingeben.',
    'Id' => 'ID',
    'Parent category:' => 'Übergeordnete Kategorie:',
    'Please fill out the following fields to category' => 'Bitte füllen Sie die folgenden Felder aus, um eine Kategorie anzulegen.',
    'Please fill out the following fields to create post.' => 'Bitte füllen Sie die folgenden Felder aus, um einen Beitrag zu erstellen.',
    'Posts' => 'Beiträge',
    'Register' => 'Registrieren',
    'Register category' => 'Kategorie registrieren',
    'Save' => 'Speichern',
    'Select category' => 'Kategorie auswählen',
    'Seo Description' => 'SEO-Beschreibung',
    'Seo H1' => 'SEO H1',
    'Seo Keywords' => 'SEO-Schlüsselwörter',
    'Seo Title' => 'SEO-Titel',
    'Seo texts' => 'SEO-Texte',
    'Slug' => 'Slug',
    'Status' => 'Status',
    'Subcategory' => 'Unterkategorie',
    'Tags' => 'Tags',
    'This category does not exist.' => 'Diese Kategorie existiert nicht.',
    'This title has already been taken.' => 'Dieser Titel ist bereits vergeben.',
    'Title' => 'Titel',
    'Update' => 'Aktualisieren',
    'Update category' => 'Kategorie aktualisieren',
    'Update posts' => 'Beiträge aktualisieren',
    'YiiVerse Blog' => 'YiiVerse Blog',
    'Your category and its sub categories have been successfully deleted.' => 'Ihre Kategorie und ihre Unterkategorien wurden erfolgreich gelöscht.',
    'Your category has been successfully deleted.' => 'Ihre Kategorie wurde erfolgreich gelöscht.',
    'Your category has been successfully disabled.' => 'Ihre Kategorie wurde erfolgreich deaktiviert.',
    'Your category has been successfully enabled.' => 'Ihre Kategorie wurde erfolgreich aktiviert.',
    'Your category has been successfully updated.' => 'Ihre Kategorie wurde erfolgreich aktualisiert.',
    'Your category has not been deleted.' => 'Ihre Kategorie wurde nicht gelöscht.',
    'Your category has not been found.' => 'Ihre Kategorie wurde nicht gefunden.',
    'Your principal category has been successfully registered.' => 'Ihre Hauptkategorie wurde erfolgreich registriert.',
    'Your sub category has been successfully registered.' => 'Ihre Unterkategorie wurde erfolgreich registriert.',
    'content_short' => 'kurzer_inhalt',
    'created_at' => 'erstellt_am',
    'tags' => 'Tags',
];
