<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Actions' => 'Akcje',
    'Add category' => 'Dodaj kategorię',
    'Add post' => 'Dodaj wpis',
    'Add subcategory' => 'Dodaj podkategorię',
    'Add, edit, delete, enable and disable categories.' => 'Dodaj, zmień, usuń, włącz lub wyłącz kategorie.',
    'Are you sure to delete this user?' => 'Na pewno usunąć tego użytkownika?',
    'Are you sure to disable this category?' => 'Na pewno wyłączyć tę kategorię?',
    'Are you sure to enable this category?' => 'Na pewno włączyć tę kategorię?',
    'By Category: {category} ({post.count})' => 'Wg. kategorii: {category} ({post.count})',
    'By Post' => 'Wg. wpisu',
    'Categories' => 'Kategorie',
    'Category' => 'Kategoria',
    'Content Short' => 'Krótka treść',
    'Create post' => 'Dodaj wpis',
    'Date' => 'Data',
    'Delete' => 'Usuń',
    'Description' => 'Opis',
    'Disable category' => 'Wyłącz kategorię',
    'Discover new releases, fresh articles, updated wikis, and engage in general' => 'Odkryj nowe wydania, świeże artykuły, aktualizowane wiki i zaangażuj się ogólnie',
    'Enable category' => 'Włącz kategorię',
    'Enter description Here.' => 'Dodaj opis.',
    'Enter slug Here.' => 'Dodaj sluga.',
    'Enter title Here.' => 'Dodaj tytuł.',
    'Filter by Category: {category}' => 'Filtrowanie wg. kategorii: {category}',
    'Follow me' => 'Obserwuj mnie',
    'Id' => 'ID',
    'Latest' => 'Najnowsze',
    'Latest ({post.count})' => 'Najnowsze ({post.count})',
    'Parent category:' => 'Nadrzędna kategoria:',
    'Please fill out the following fields to category' => 'Proszę wypełnić pola kategorii.',
    'Please fill out the following fields to create post.' => 'Proszę wypełnić pola aby utworzyć wpis.',
    'Posts' => 'Wpisy',
    'Read more' => 'Czytaj więcej',
    'Register' => 'Rejestracja',
    'Register category' => 'Utwórz kategorię',
    'Save' => 'Zapisz',
    'Select category' => 'Wybierz kategorię',
    'Seo Description' => 'Opis SEO',
    'Seo H1' => 'H1 SEO',
    'Seo Keywords' => 'Słowa kluczowe SEO',
    'Seo Title' => 'Tytuł SEO',
    'Seo texts' => 'Treść SEO',
    'Slug' => 'Slug',
    'Status' => 'Status',
    'Stay updated with the latest news and announcements on YiiFramework.' => 'Bądź na bieżąco z najnowszymi wiadomościami i ogłoszeniami na temat YiiFramework.',
    'Subcategory' => 'Podkategoria',
    'Tags' => 'Tagi',
    'This category does not exist.' => 'Ta kategoria nie istnieje.',
    'This title has already been taken.' => 'Ten tytuł został już wykorzystany.',
    'Title' => 'Tytuł',
    'Update' => 'Zmiana',
    'Update category' => 'Zmiana kategorii',
    'Update posts' => 'Zmiana wpisu',
    'Your category and its sub categories have been successfully deleted.' => 'Kategoria oraz jej podkategorie zostały usunięte.',
    'Your category has been successfully deleted.' => 'Kategoria została usunięta.',
    'Your category has been successfully disabled.' => 'Kategoria została wyłączona.',
    'Your category has been successfully enabled.' => 'Kategoria została włączona.',
    'Your category has been successfully updated.' => 'Kategoria została zmieniona.',
    'Your category has not been deleted.' => 'Kategoria nie została usunięta.',
    'Your category has not been found.' => 'Kategoria nie została znaleziona.',
    'Your principal category has been successfully registered.' => 'Główna kategoria została utworzona.',
    'Your sub category has been successfully registered.' => 'Podkategoria została utworzona.',
    'created_at' => 'Utworzono',
    'discussions within the Yii community. ' => 'dyskusje w społeczności Yii.',
    'tags' => 'tagi',
];
