<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Actions' => 'Acciones',
    'Add category' => 'Agregar categoría',
    'Add post' => 'Agregar publicación',
    'Add subcategory' => 'Agregar subcategoría',
    'Add, edit, delete, enable and disable categories.' => 'Agregar, editar, eliminar, habilitar y deshabilitar categorías.',
    'Are you sure to delete this user?' => '¿Estás seguro de eliminar a este usuario?',
    'Are you sure to disable this category?' => '¿Estás seguro de deshabilitar esta categoría?',
    'Are you sure to enable this category?' => '¿Estás seguro de habilitar esta categoría?',
    'By Category: {category} ({post.count})' => 'Por categoría: {category} ({post.count})',
    'By Post' => 'Por publicación',
    'Categories' => 'Categorías',
    'Category' => 'Categoría',
    'Content Short' => 'Contenido corto',
    'Create post' => 'Crear publicación',
    'Date' => 'Fecha',
    'Delete' => 'Eliminar',
    'Description' => 'Descripción',
    'Disable category' => 'Deshabilitar categoría',
    'Discover new releases, fresh articles, updated wikis, and engage in general' => 'Descubre nuevos lanzamientos, artículos frescos, wikis actualizados y participa en general',
    'Enable category' => 'Habilitar categoría',
    'Enter description Here.' => 'Ingresa la descripción aquí.',
    'Enter slug Here.' => 'Ingresa el slug aquí.',
    'Enter title Here.' => 'Ingresa el título aquí.',
    'Explore now' => 'Explora ahora',
    'Filter by Category: {category}' => 'Filtrar por categoría: {category}',
    'Follow me' => 'Sigueme',
    'Id' => 'ID',
    'Latest' => 'Lo ultimo',
    'Latest ({post.count})' => 'Lo ultimo ({post.count})',
    'Parent category:' => 'Categoría padre:',
    'Please fill out the following fields to category' => 'Por favor, completa los siguientes campos para la categoría',
    'Please fill out the following fields to create post.' => 'Por favor, completa los siguientes campos para crear la publicación.',
    'Posts' => 'Publicaciones',
    'Read more' => 'Leer más',
    'Register' => 'Registrar',
    'Register category' => 'Registrar categoría',
    'Save' => 'Guardar',
    'Select category' => 'Seleccionar categoría',
    'Seo Description' => 'Descripción SEO',
    'Seo H1' => 'SEO H1',
    'Seo Keywords' => 'Palabras clave SEO',
    'Seo Title' => 'Título SEO',
    'Seo texts' => 'Textos SEO',
    'Slug' => 'Slug',
    'Status' => 'Estado',
    'Stay updated with the latest news and announcements on YiiFramework.' => 'Mantente actualizado con las últimas noticias y anuncios sobre YiiFramework.',
    'Subcategory' => 'Subcategoría',
    'Tags' => 'Etiquetas',
    'This category does not exist.' => 'Esta categoría no existe.',
    'This title has already been taken.' => 'Este título ya ha sido tomado.',
    'Title' => 'Título',
    'Update' => 'Actualizar',
    'Update category' => 'Actualizar categoría',
    'Update posts' => 'Actualizar publicaciones',
    'Your category and its sub categories have been successfully deleted.' => 'Tu categoría y sus subcategorías se han eliminado correctamente.',
    'Your category has been successfully deleted.' => 'Tu categoría se ha eliminado correctamente.',
    'Your category has been successfully disabled.' => 'Tu categoría se ha deshabilitado correctamente.',
    'Your category has been successfully enabled.' => 'Tu categoría se ha habilitado correctamente.',
    'Your category has been successfully updated.' => 'Tu categoría se ha actualizado correctamente.',
    'Your category has not been deleted.' => 'Tu categoría no se ha eliminado.',
    'Your category has not been found.' => 'Tu categoría no se ha encontrado.',
    'Your principal category has been successfully registered.' => 'Tu categoría principal se ha registrado correctamente.',
    'Your sub category has been successfully registered.' => 'Tu subcategoría se ha registrado correctamente.',
    'created_at' => 'creado_en',
    'discussions within the Yii community.' => 'discusiones dentro de la comunidad Yii.',
    'tags' => 'etiquetas',
];
